name: Build

on:
  push:
    branches: master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: test
        run: cargo test --release
      - name: build
        run: cargo build --release
      - name: store-executable
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: target/release/xzibot
